FROM ubuntu:16.04

RUN apt-get update -y && sudo apt-get upgrade -y && \
    apt-get install -y ganglia-monitor ganglia-monitor-python && \
    apt-get clean

RUN mkdir -p /usr/lib/ganglia/python_modules/ && \
    chown nobody:nogroup /usr/lib/ganglia/python_modules/ && \ 
    mv /etc/ganglia/gmond.conf /etc/ganglia/gmond.conf.bac
